/*
 * FILE:        factor.c
 * AUTHOR:      Artem Mavrin
 * UPDATED:     2016-01-09
 * DESCRIPTION: Prints out the prime factors of a given positive integer.
 *              Prime factors are computed using trial division with wheel
 *              factorization.
 */

#include <stdio.h>
#include <stdlib.h>
#include "wheel.h"

const unsigned long basePrimes[] = {2, 3, 5, 7, 11, 13};
const unsigned long numBasePrimes = 6;

unsigned long factor(unsigned long num, int unique, FILE *stream) {
    Wheel *wheel;               /* The wheel used in the algorithm */
    unsigned long index;        /* Track position in loops */
    unsigned long count = 0;    /* The number of divisors */
    unsigned long prime;        /* A potentially prime number */

    /* 0 and 1 have no prime factors */
    if (num < 2)
        return 0;

    /* Divide by the base primes */
    for (index = 0; index < numBasePrimes; index++) {
        prime = basePrimes[index];
        if (unique) {
            if (num % prime == 0) {
                if (stream) fprintf(stream, "%lu\n", prime);
                count++;
                /* Divide num by prime as many times as possible */
                for (num /= prime; num % prime == 0; num /= prime);
            }
        } else {
            /* Divide num by prime as many times as possible */
            while (num % prime == 0) {
                if (stream) fprintf(stream, "%lu\n", prime);
                num /= prime;
                count++;
            }
        }
    }

    /* Create the wheel to get the next potential prime divisors */
    wheel = newWheel(basePrimes, numBasePrimes);

    /* Divide by the prime candidates generated by the wheel */
    while (num > 1) {
        prime = nextp(wheel);
        if (prime * prime > num) {
            if (stream) fprintf(stream, "%lu\n", num);
            count++;
            break;
        } else if (unique) {
            if (num % prime == 0) {
                if (stream) fprintf(stream, "%lu\n", prime);
                count++;
                /* Divide num by prime as many times as possible */
                for (num /= prime; num % prime == 0; num /= prime);
            }
        } else {
            /* Divide num by prime as many times as possible */
            while (num % prime == 0) {
                if (stream) fprintf(stream, "%lu\n", prime);
                num /= prime;
                count++;
            }
        }
    }

    deleteWheel(&wheel);
    return count;
}
